### ISSUE TITLE
Home page lead text 

### ISSUE THREAD

**Issue by tomkuk** [polyconf/polyconf.com#1]
Lead text "POLYGLOT PROGRAMMERS UNITE" is placed under logo
![polyconf polyglot programming conference](https://cloud.githubusercontent.com/assets/327658/12423160/68e2d7d0-beca-11e5-9cef-69bef3ab9bed.png)

**Comment by pawelwodkowski** [comment]
Resize window?

**Comment by zaiste** [comment]
@pawelwodkowski the same here, it's max screen size

**Comment by pawelwodkowski** [comment]
Ok.

**Comment by pawelwodkowski** [comment]
Done.
