### ISSUE TITLE
General/ the empty spaces between elements are too big, should be smaller

### ISSUE THREAD

**Issue by agnieszkabukowska** [polyconf/polyconf.com#10]
![zrzut ekranu 2016-01-19 o 17 07 56](https://cloud.githubusercontent.com/assets/11835317/12424192/4228381a-becf-11e5-9cc5-1c3c4b69bf49.png)
![zrzut ekranu 2016-01-19 o 17 08 16](https://cloud.githubusercontent.com/assets/11835317/12424193/425176da-becf-11e5-9424-474d32e30682.png)

**Comment by pawelwodkowski** [comment]
Done.

**Comment by agnieszkabukowska** [comment]
@pawelwodkowski @zaiste I don't see the difference

**Comment by pawelwodkowski** [comment]
Jest zmniejszone o 50 pikseli. Tak ma być :)

**Comment by pawelwodkowski** [comment]
![4228381a-becf-11e5-9cc5-1c3c4b69bf49_png_977x496_pikseli_i_polyconf_-_polyglot_programming_conference](https://cloud.githubusercontent.com/assets/407311/12447036/e5f4690c-bf6d-11e5-9c69-b0a526122ceb.png)
