### ISSUE TITLE
Eventil - Logo letters are cutted

### ISSUE THREAD

**Issue by agnieszkabukowska** [polyconf/polyconf.com#4]
http://eventil.com/events/polyconf-16
![zrzut ekranu 2016-01-19 o 16 49 12](https://cloud.githubusercontent.com/assets/11835317/12423625/9c5d4eb8-becc-11e5-8b50-d84668709d94.png)

**Comment by zaiste** [comment]
@agnieszkabukowska this should be reported here: https://github.com/eventil/support
