### ISSUE TITLE
About/ Tweeter feed bug - no avatars, empty spaces

### ISSUE THREAD

**Issue by agnieszkabukowska** [polyconf/polyconf.com#8]
![zrzut ekranu 2016-01-19 o 16 55 27](https://cloud.githubusercontent.com/assets/11835317/12423781/7f6c3bc4-becd-11e5-8d3b-172b577af8ba.png)

**Comment by pawelwodkowski** [comment]
Done.

**Comment by agnieszkabukowska** [comment]
@pawelwodkowski @zaiste I don't see the difference
